
name: Build
on: [push, pull_request]

env:
  DOTNET_NOLOGO: 1
  BUILD_DOTNET_VERSION: 7.0.x

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.BUILD_DOTNET_VERSION }}

      - name: NuGet Restore
        run: dotnet restore src/InlineIL.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore src/InlineIL.sln

      - name: NuGet Pack
        run: dotnet pack --configuration Release --no-build src/InlineIL.sln

      - name: Upload NuGet
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: output/*.nupkg

  test:
    name: Test (${{ matrix.configuration }}, C# ${{ matrix.langVersion }})
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        langVersion: [10, 11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.BUILD_DOTNET_VERSION }}

      - name: Test
        run: dotnet test --configuration ${{ matrix.configuration }} -p:TestAssembliesLangVersion=${{ matrix.langVersion }} src/InlineIL.sln
